### ISSUE TITLE
can we read user metadata from orc?

### ISSUE THREAD

**Issue by dattem** [scritchley/orc#52]
Is there a way we can read orc user metadata using this library ? If yes, can you guide me through how to do that?

**Comment by scritchley** [comment]
Currently the footer (which includes the user metadata) isn't accessible publicly from the Reader implementation here: https://github.com/scritchley/orc/blob/master/reader.go#L30

It would be possible and fairly straighforward to expose it through a getter method? Happy to review a PR if you want to give it a go?

Otherwise, I will look at adding it in a future update.
